server.port=8080
spring.application.name=nfl-pickem-api

spring.data.mongodb.uri=mongodb+srv://fiap:JAVADEV44@cluster0.uxooxid.mongodb.net/NFLPickEm?authSource=admin&retryWrites=true&w=majority
spring.data.mongodb.auto-index-creation=true